LFDT-web3j/web3j-evm

build.gradle
gradle/jacoco/build.gradle
gradle/java/build.gradle
gradle/javadoc/build.gradle
gradle/publish/build.gradle
gradle/repositories/build.gradle
gradle/spotless/build.gradle
gradle/spotless/formatter.properties
gradle/spotless/java.license
src/main/java/org/web3j/evm/Demo.java
src/test/java/org/web3j/protocol/core/CoreIT.java
src/test/java/org/web3j/protocol/core/IntegrationTestConfig.java
src/test/java/org/web3j/protocol/core/TestnetConfig.java

Reused parts from build.gradle in web3j-unit related to release setup, needs a review..

Reuse parts from web3j-unit for release setup

---

src/main/kotlin/org/web3j/evm/ConsoleDebugTracer.kt
src/main/kotlin/org/web3j/evm/PassthroughTracer.kt

Various improvements made to debug tracers

Console debug tracer improvements

---

gradle.properties

*required*
*required*
*required*

bumped version

---

gradle.properties
gradle/publish/build.gradle
gradle/spotless/build.gradle
src/main/kotlin/org/web3j/evm/EmbeddedEthereum.kt

Fixed type inference error.
*required*
*required*
*required*

Bump version.

---

README.md

*required*
*required*
*required*

Bump Readme Versions

---

build.gradle

Changed koltin versions to be the same
*required*
*required*
*required*

Updated Kotlin Version

---

build.gradle
gradle/repositories/build.gradle

*required*
*required*
*required*

Temporary disables build.gradle overwrite

---

build.gradle
src/main/kotlin/org/web3j/evm/Configuration.kt
src/main/kotlin/org/web3j/evm/EmbeddedEthereum.kt
src/main/kotlin/org/web3j/evm/EmbeddedWeb3jService.kt
src/main/kotlin/org/web3j/evm/InMemoryBesuChain.kt
src/test/java/org/web3j/protocol/core/CoreIT.java

*required*
*required*
*required*

Multiple accounts

---

build.gradle

Updates Log4J and Besu versions to protect against Log4Shell
Build.gradle
Improves security

update_log4j_and_besu_versions to protect against log4shell

---

README.md
gradle.properties

*required*
*required*
*required*

Prepare for 4.9.1

---

build.gradle

Fix dependency build issue
To work with another projects properly

fix dependency issue

---

build.gradle
gradle.properties
src/main/kotlin/org/web3j/evm/EmbeddedEthereum.kt

*required*
*required*
*required*

Fix hex issue

---

README.md
build.gradle
gradle.properties

*required*
*required*
*required*

Prepare for 4.9.4

---

build.gradle
gradle.properties

*required*
*required*
*required*

bump version

---

README.md
build.gradle
gradle.properties

prepare for 4.9.8

---

gradle.properties

*required*
*required*
*required*

update to next snapshot version

---

README.md
build.gradle
gradle.properties

*required*
*required*
*required*

bump version 4.10.3 snapshot

---

README.md
build.gradle
gradle.properties
gradle/spotless/build.gradle
src/main/kotlin/org/web3j/evm/EmbeddedEthereum.kt
src/main/kotlin/org/web3j/evm/InMemoryBesuChain.kt

*required*
*required*
*required*

bump versions

---

build.gradle
gradle.properties
src/main/kotlin/org/web3j/evm/EmbeddedEthereum.kt
src/main/kotlin/org/web3j/evm/InMemoryBesuChain.kt

*required*
*required*
*required*

Besu upgrade

---

CHANGELOG.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
MAINTAINERS.md
SECURITY.md

Files added for repo migration
all
https://toc.hyperledger.org/guidelines/repository-structure.html

Files added for repo migration

---

CHANGELOG.md
build.gradle
gradle.properties

bump snapshot version 4.11.2
*required*
*required*

bump snapshot version 4.11.2

---

CHANGELOG.md
build.gradle

Updates web3j version as it was missed in bump snapshot version PR - https://github.com/hyperledger/web3j-evm/pull/104
*required*
Missed during bump snapshot version PR - https://github.com/hyperledger/web3j-evm/pull/104

web3j version update

---

.github/workflows/release.yml
CHANGELOG.md

*required*
*required*
*required*

Repo owner changed

---

CHANGELOG.md
README.md
build.gradle
gradle.properties

*required*
*required*
*required*

Bump snapshot version to 4.11.4

---

CHANGELOG.md
README.md
build.gradle
gradle.properties

Bump snapshot 4.12.1
*required*
Bump snapshot 4.12.1

Bump snapshot 4.12.1

---

CHANGELOG.md
README.md
build.gradle
gradle.properties

*required*
*required*
*required*

Bump 4.12.2 SNAPSHOT

---

CHANGELOG.md
README.md
build.gradle
gradle.properties

Updates snapshot version to 4.12.3
*required*
*required*

Bump snapshot to 4.12.3

---

.github/workflows/release.yml
CHANGELOG.md
build.gradle
gradle.properties

*required*
*required*
*required*

bump 4.12.4

---

build.gradle

*required*
*required*
*required*

bump web3j

---

CHANGELOG.md
README.md
build.gradle
gradle.properties

*required*
*required*
*required*

Bump 4.13.1 snapshot

---

.github/workflows/build.yml
.github/workflows/publish-snapshot.yml
.github/workflows/release.yml
CHANGELOG.md
build.gradle
gradle/java/build.gradle
src/main/kotlin/org/web3j/evm/EmbeddedEthereum.kt
src/main/kotlin/org/web3j/evm/InMemoryBesuChain.kt

*required*
*required*
*required*

upgrade besu version

---

.github/workflows/release.yml
CHANGELOG.md
README.md
build.gradle
gradle.properties
gradle/publish/build.gradle
gradle/spotless/build.gradle

*required*
*required*
*required*

Bump 4.14.1 snapshot
